MyContact/src/Entity/Contact.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ContactRepository")
 * @UniqueEntity("numero")
 *  @Vich\Uploadable
 */
class Contact
{

    const STATUS = [
        0=>'En ligne',
        1=>'Hors ligne'
    ];
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="contact_image", fileNameProperty="filename")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $prenom;

    /**
     * @ORM\Column(type="integer")
     */
    private $numero;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $email;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $status;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * Contact constructor.
     * @throws \Exception
     */
    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }
    public function getSlug():string
    {
        return  (new Slugify())-> slugify($this->prenom);
    }

    public function getNumero(): ?int
    {
        return $this->numero;
    }



    public function setNumero(int $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }
    public function getStatusType(): string
    {
        if($this->getStatus()!=1){
            return"Hors ligne ";
        }
        else{
            return "En ligne";
        }
    }


    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param string|null $filename
     * @return Contact
     */
    public function setFilename(?string $filename): Contact
    {
        $this->filename = $filename;
        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return Contact
     * @throws \Exception
     */
    public function setImageFile(?File $imageFile): Contact
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }



}

MyContact/src/Form/ContactType.php
<?php

namespace App\Form;

use App\Entity\Contact;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContactType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('numero')
            ->add('email')
            ->add('status', null, [
                'label'=>'En ligne'
            ])
            ->add('imageFile',FileType::class, [
                'required'=>false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Contact::class,
        ]);
    }
}

MyContact/src/Controller/ContactController.php
<?php
/**
 * Created by PhpStorm.
 * User: HP
 * Date: 07/03/2019
 * Time: 07:22
 */

namespace App\Controller;


use App\Entity\Contact;
use App\Entity\ContactSearch;
use App\Form\ContactSearchType;
use App\Repository\ContactRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ContactController extends AbstractController {


    /**
     * @var ContactRepository
     */
    private $repository;

    public function __construct(ContactRepository $repository)
    {

        $this->repository = $repository;
    }

    /**
     * @Route("/contacts", name="contact.index")
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request):Response
    {

        $search = new ContactSearch();
        $form = $this->createForm(ContactSearchType::class, $search);
        $form->handleRequest($request);

        $contacts = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page',1),
            12
        );
        return $this->render('contact/index.html.twig', [
            'current_menu' => 'contacts',
            'contacts' => $contacts,
            'form'  =>$form->createView()
        ]);
    }

    /**
     * * @Route("/contacts/{slug}-{id}", name="contact.show", requirements={"slug": "[a-z0-9\-]*"})
     * @param Contact $contact
     * @param string $slug
     * @return Response
     */
    public function  show(Contact $contact, string $slug):Response
    {
        if ($contact->getSlug() !== $slug) {
            return $this -> redirectToRoute('contact.show',[
                'id'=> $contact->getId(),
                'slug' => $contact->getSlug()
            ],301);
        }
        return$this->render('contact/show.html.twig',[
            'contact' => $contact,
            'current_menu' => 'contacts'

        ]);

    }
}

MyContact/templates/contact/_contact.html.twig
<div class="card mb-4">

    {% if contact.filename %}
        <img src="{{ vich_uploader_asset(contact, 'imageFile') | imagine_filter('thumb')}}" alt="card-img-top" style="width: 100%; height: 500px;">
    {% else %}
        <img src=" /images/contacts/logo.png" alt="card-img-top" style="width: 100%; height: 500px;">
    {% endif %}
    <div class="card-body">

        <h5 class="card-title">
            <a href="{{ path('contact.show', {slug: contact.slug, id: contact.id}) }}">
                {{ contact.prenom }}
            </a>
        </h5>
        <p class="card-text" style="font-weight: bold;font-size: 1.5rem">+221 {{  contact.numero }}</p>
    </div>
</div>

MyContact/templates/contact/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'My Contacts' %}
{% block body %}
    <div class="jumbotron">
        <div class="container">
            {{ form_start(form) }}
            <div class="form-row">
                <div class="col">
                    {{ form_row(form.findContactByPrenom) }}
                </div>
                <div class="col">
                    {{ form_row(form.findContactByNom) }}
                </div>
                <div class="col">
                    {{ form_row(form.findContactByNumero) }}
                </div>
                <div class="col">
                    <button class="btn btn-primary">Rechercher</button>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
    <div class="container mt-4">

        <h1>Mes Contacts</h1>
        <div class="row">


            {% for contact in contacts %}
                <div class="col-md-3">
                    {% include 'contact/_contact.html.twig' %}
                </div>
            {% endfor %}

        </div>

        <div class="navigation">
            {{ knp_pagination_render(contacts) }}
        </div>

    </div>

{% endblock %}

MyContact/templates/contact/show.html.twig
{% extends 'base.html.twig' %}
{% block title contact.prenom %}
{% block body %}
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-2">
                    {% if contact.filename %}
                        <img src="{{ vich_uploader_asset(contact, 'imageFile') | imagine_filter('medium')}}" alt="card-img-top" style="width: 100%; height: auto;">
                    {% else %}
                        <img src=" /images/contacts/logo.png" alt="card-img-top" style="width: 100%; height: auto">

                    {% endif %}
                </div>
                <div class="col-md-6">
                    <h1>{{ contact.prenom }}</h1>
                    <h2>{{ contact.numero }}</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-4">


        <div class="row">
            <div class="col-md-8">


                <h2>Details du contact</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Prenom</td>
                        <td>{{ contact.prenom }}</td>
                    </tr>
                    <tr>
                        <td>Nom</td>
                        <td>{{ contact.nom }}</td>
                    </tr>
                    <tr>
                        <td>Numero</td>
                        <td>{{ contact.numero }}</td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td>{{ contact.email }}</td>
                    </tr>
                    <tr>
                        <td>Statut</td>
                        <td>{{ contact.statusType }}</td>
                    </tr>

                </table>
            </div>
            <div class="col-md-4">

            </div>

        </div>

    </div>

{% endblock %}